POST  http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1Njg3NzVlZjFlZmM2NzJiNjQ4OGM3NiIsImlhdCI6MTcwMTM1NjA1Nn0.izqULo6wkvQg0WkXaAVj94truErsR7ojnmSr1XqSenA

{
    "title": "Blogi kaloista",
    "author": "Viljami",
    "url": "localhost:3003/api/blogs",
    "likes": 100,
    "user":"656863cdb29f218cc063b93e"
}